[package]
name = "remove"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.28"
tokio = { version = "1.30.0", features = ["macros","fs", "rt-multi-thread"] }
clap = { version = "4.3.21", features = ["derive"] }
async-recursion = "1.0.4"
