[package]
name = "remove"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.31"
tokio = { version = "1.40.0", features = ["macros", "fs", "rt-multi-thread"] }
clap = { version = "4.5.20", features = ["derive"] }
async-recursion = "1.1.1"
