[package]
name = "url_search"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.40.0"
reqwest = { version = "0.12.13", features = ["blocking"] }
thiserror = "2.0.12"
