[package]
name = "url_search"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.39.0"
reqwest = { version = "0.12.12", features = ["blocking"] }
thiserror = "2.0.11"
