name: Tech Request
description: File a tech request
title: '[Tech]: '
labels: ['tech']
assignees:
  - suxiaoshao
body:
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: Which product has a tech request?
      options:
        - feiwen
        - Hclipboard
        - http-client
        - movie
        - others
        - others
        - all
    validations:
      required: true
  - type: checkboxes
    id: component
    attributes:
      label: Component
      description: Which component has a tech request?
      options:
        - label: tauri
        - label: web
        - label: devops
        - label: docs
  - type: textarea
    id: requirement
    attributes:
      label: Requirement
    validations:
      required: true
  - type: textarea
    id: background
    attributes:
      label: Background
    validations:
      required: true
  - type: textarea
    id: objectives
    attributes:
      label: Objectives
    validations:
      required: true
  - type: textarea
    id: solutions_and_suggestions
    attributes:
      label: Your solutions and suggestions
      description: Please describe your solutions and suggestions.
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: anything_else
    attributes:
      label: Anything else
      description: Please provide any other information that may be helpful.
    validations:
      required: false
